Implement new version of `@inubekit/foundations` `<Icon>
selsa-inube/inubekit-icon pull request #6
Opened 2024-02-19 17:49 UTC by Andresbl123

implement the new token version, updated in the **@inubekit/foundations** library, which allows for scalability and customisation on a more individual basis

2024-02-19 19:10 UTC, JanuarAsprilla approved these changes

2024-02-21 17:36 UTC, JanuarAsprilla approved these changes

2024-02-21 20:00 UTC, wfercanas requested changes

2024-02-21 20:17 UTC, cmarin001 commented on src/Icon/props.ts
>  const appearances = [
solved

2024-02-21 21:11 UTC, cmarin001 commented on src/Icon/Icon.stories.tsx
solved

2024-02-21 21:39 UTC, cmarin001 commented on src/Icon/styles.js
>      if (!filledAppearancesWithGrayIcon.includes($appearance))
solved

2024-02-22 15:17 UTC, JanuarAsprilla approved these changes

2024-02-22 16:40 UTC, wfercanas approved these changes

2024-02-22 16:40 UTC, merged